executable   = /fast/sliu/wanqi/MultiBitsQ/scripts/3_paretoq_1bit_llama3_1B.sh
output       = llama3-1B_1bit_12wsteps_bs128_lr2e-5_paretoq.$(Process).out
error        = llama3-1B_1bit_12wsteps_bs128_lr2e-5_paretoq.$(Process).err
log          = llama3-1B_1bit_12wsteps_bs128_lr2e-5_paretoq.log
request_cpus = 8
request_memory = 160000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1
