executable   = /home/sliu/kwang/MultiBitsQ/scripts/0_asym_llama3_1b.sh
output       = llama3_1b_234bit_12wsteps_bs128_lr2e-5_wonoise_asym.$(Process).out
error        = llama3_1b_234bit_12wsteps_bs128_lr2e-5_wonoise_asym.$(Process).err
log          = llama3_1b_234bit_12wsteps_bs128_lr2e-5_wonoise_asym.log
request_cpus = 8
request_memory = 160000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1
