executable   = /fast/sliu/kwang/MultiBitsQ/scripts/0_asym_llama3_1b.sh
output       = llama3_1b_234bit_10wsteps_bs128_lr5e-4_wonoise_lsq.$(Process).out
error        = llama3_1b_234bit_10wsteps_bs128_lr5e-4_wonoise_lsq.$(Process).err
log          = llama3_1b_234bit_10wsteps_bs128_lr5e-4_wonoise_lsq.log
request_cpus = 8
request_memory = 160000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1
