executable   = /home/sliu/kwang/MultiBitsQ/scripts/0_baseline.sh
output       = llama3-1B_234bit_12wsteps_bs128_lr2e-5_wonoise.$(Process).out
error        = llama3-1B_234bit_12wsteps_bs128_lr2e-5_wonoise.$(Process).err
log          = llama3-1B_234bit_12wsteps_bs128_lr2e-5_wonoise.log
request_cpus = 8
request_memory = 160000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1
