executable   = /home/wangk/MultiBitsQ/scripts/0_llama3_1b_random_0_7.sh
output       = Llama3_1B_234bit_12wsteps_bs128_lr2e-5_rebuild_random_0_7.$(Process).out
error        = Llama3_1B_234bit_12wsteps_bs128_lr2e-5_rebuild_random_0_7.$(Process).err
log          = Llama3_1B_234bit_12wsteps_bs128_lr2e-5_rebuild_random_0_7.log
request_cpus = 8
request_memory = 960000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1