executable   = /home/wangk/MultiBitsQ/scripts/0_llama3_1b_random_0_3_124_221.sh
output       = Llama3_1B_124bit_2wsteps_bs128_lr2e-5_rebuild_random_0_3_221.$(Process).out
error        = Llama3_1B_124bit_2wsteps_bs128_lr2e-5_rebuild_random_0_3_221.$(Process).err
log          = Llama3_1B_124bit_2wsteps_bs128_lr2e-5_rebuild_random_0_3_221.log
request_cpus = 8
request_memory = 960000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1