executable   = /home/wangk/MultiBitsQ/scripts/0_Llama3_1B.sh
output       = Llama3_1B_234bit_12wsteps_bs128_lr2e-4_wonoise.$(Process).out
error        = Llama3_1B_234bit_12wsteps_bs128_lr2e-4_wonoise.$(Process).err
log          = Llama3_1B_234bit_12wsteps_bs128_lr2e-4_wonoise.log
request_cpus = 8
request_memory = 160000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1
