executable   = /fast/sliu/wanqi/MultiBitsQ/scripts/1_noise_inject.sh
output       = mobilellm_125M_234bit_12wsteps_bs128_lr2e-5_w_noise.$(Process).out
error        = mobilellm_125M_234bit_12wsteps_bs128_lr2e-5_w_noise.$(Process).err
log          = mobilellm_125M_234bit_12wsteps_bs128_lr2e-5_w_noise.log
request_cpus = 8
request_memory = 160000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1
