executable   = /home/sliu/kwang/MultiBitsQ/scripts/1_noise_inject.sh
output       = llama3-1B_234bit_12wsteps_bs128_lr2e-5_w_noise_0001_0001.$(Process).out
error        = llama3-1B_234bit_12wsteps_bs128_lr2e-5_w_noise_0001_0001.$(Process).err
log          = llama3-1B_234bit_12wsteps_bs128_lr2e-5_w_noise_0001_0001.log
request_cpus = 8
request_memory = 160000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1
