executable   = /home/sliu/kwang/MultiBitsQ/scripts/run.sh
output       = 2ndtrain_mobilellm_125M_234bit_12wsteps_bs128_lr2e-5_wonoise_fixrand.$(Process).out
error        = 2ndtrain_mobilellm_125M_234bit_12wsteps_bs128_lr2e-5_wonoise_fixrand.$(Process).err
log          = 2ndtrain_mobilellm_125M_234bit_12wsteps_bs128_lr2e-5_wonoise_fixrand.log
request_cpus = 8
request_memory = 160000
request_gpus = 8
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")
Queue 1
