torchrun --nnodes=1 --nproc_per_node=1 train.py \
--local_dir "/tmp/llama_test/" \
--input_model_filename "meta-llama/Llama-3.2-1B" \
--output_model_filename "test-quick" \
--train_data_local_path "/tmp/train.jsonl" \
--do_train True \
--do_eval False \
--model_max_length 256 \
--bf16 True \
--num_train_epochs 1 \
--per_device_train_batch_size 8 \
--gradient_accumulation_steps 1 \
--save_steps 50 \
--logging_steps 5 \
--qat True \
--w_bits_list "2,4" \
--noise_injection True \
--pre_quantization_noise True \
--multiple_bits_random_assign True